# NUMPY PRACTICE 

1. Create NumPy array from Python list

In [1]:
import numpy as np

my_list = np.array([1, 2, 3, 4, 5])
my_list.shape

(5,)

In [2]:
my_list.dtype

dtype('int64')

2. Mean, median, std using NumPy

In [3]:
numbers = np.array([20, 30, 40, 50, 60])

num_mean = np.mean(numbers)
num_median = np.median(numbers)
num_std = np.std(numbers).astype(int)

print('num_mean:', num_mean)
print('num_median:', num_median)
print('num_std:', num_std)

num_mean: 40.0
num_median: 40.0
num_std: 14


3. Replace values in NumPy array

In [4]:
arr = np.array([10, 15, 20, 25, 30])

arr[arr > 20] = 100
print(arr)


[ 10  15  20 100 100]


4. NumPy array filtering

In [5]:
arr = np.array([3, 7, 10, 15, 20, 25, 30])

filtered = arr[arr > 20]
filtered
  


array([25, 30])

In [6]:
filtered = arr > 20  # boolean
filtered

array([False, False, False, False, False,  True,  True])

5. Reshape NumPy array

In [7]:
arr = np.array([1,2,3,4,5,6,7,8])
new = arr.reshape(2,2,2)
print(new)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
